## Lab Task 1
Write a Python program that multiplies a TensorFlow tensor by a scalar value and prints the result.

In [2]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
tensor = tf.constant([[1, 2], [3, 4]])
scalar = tf.constant(5)
result = tensor * scalar
ssn = tf.compat.v1.Session()
ssn.run(result)

array([[ 5, 10],
       [15, 20]])

## Lab Task 2
Write a Python program that uses TensorFlow to compute the dot product of two vectors (1-D tensors).

In [13]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
v1 = tf.constant([24.0, 31.0], dtype=tf.float32)
v2 = tf.constant([6.0, 8.0], dtype=tf.float32)

dot_product = tf.reduce_sum(tf.multiply(v1, v2))

ssn = tf.compat.v1.Session()
dot_product_value = ssn.run(dot_product)
print("Vector 1:", v1_value)
print("Vector 2:", v2_value)
print("Dot Product:", dot_product_value)


Vector 1: [24. 31.]
Vector 2: [6. 8.]
Dot Product: 392.0


## Lab Task 3
Write a TensorFlow program that creates two matrices, matrix1 and matrix2, with the following values:
matrix1 = [[1, 2],
                 [3, 4]]
matrix2 = [[5, 6],
                [7, 8]]
Perform the athematic operations on these matrices.


In [19]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
matrix1 = tf.constant([[1, 2],
                       [3, 4]], dtype=tf.float32)
matrix2 = tf.constant([[5, 6],
                       [7, 8]], dtype=tf.float32)
addition_result = tf.add(matrix1, matrix2)

subtraction_result = tf.subtract(matrix1, matrix2)

element_wise_multiplication_result = tf.multiply(matrix1, matrix2)

matrix_multiplication_result = tf.matmul(matrix1, matrix2)

ssn = tf.compat.v1.Session()    
add_res, sub_res, ele_mul_res, mat_mul_res = ssn.run([addition_result, subtraction_result, 
                                                           element_wise_multiplication_result, 
                                                           matrix_multiplication_result])
print("Matrix1 + Matrix2:")
print(add_res)
print("\nMatrix1 - Matrix2:")
print(sub_res)
print("\nElement-wise multiplication of Matrix1 and Matrix2:")
print(ele_mul_res)
print("\nMatrix multiplication of Matrix1 and Matrix2:")
print(mat_mul_res)


Matrix1 + Matrix2:
[[ 6.  8.]
 [10. 12.]]

Matrix1 - Matrix2:
[[-4. -4.]
 [-4. -4.]]

Element-wise multiplication of Matrix1 and Matrix2:
[[ 5. 12.]
 [21. 32.]]

Matrix multiplication of Matrix1 and Matrix2:
[[19. 22.]
 [43. 50.]]


# Exercises


##### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [22]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

vector = tf.constant([1, 2, 3, 4], dtype=tf.float32)

scalar = tf.constant(5, dtype=tf.float32)

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]], dtype=tf.float32)

tensor = tf.constant([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]], dtype=tf.float32)

sess = tf.compat.v1.Session()
print("Vector:")
print(sess.run(vector))
print("\nScalar:")
print(sess.run(scalar))
print("\nMatrix:")
print(sess.run(matrix))
print("\nTensor:")
print(sess.run(tensor))


Vector:
[1. 2. 3. 4.]

Scalar:
5.0

Matrix:
[[1. 2. 3.]
 [4. 5. 6.]]

Tensor:
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


##### 2. Find the shape, rank and size of the tensors you created in 1.

In [24]:
sess = tf.compat.v1.Session()

vector_shape = sess.run(tf.shape(vector))
scalar_shape = sess.run(tf.shape(scalar))
matrix_shape = sess.run(tf.shape(matrix))
tensor_shape = sess.run(tf.shape(tensor))

vector_rank = sess.run(tf.rank(vector))
scalar_rank = sess.run(tf.rank(scalar))
matrix_rank = sess.run(tf.rank(matrix))
tensor_rank = sess.run(tf.rank(tensor))

vector_size = sess.run(tf.size(vector))
scalar_size = sess.run(tf.size(scalar))
matrix_size = sess.run(tf.size(matrix))
tensor_size = sess.run(tf.size(tensor))

print("Vector:")
print("Shape:", vector_shape, "Rank:", vector_rank, "Size:", vector_size)

print("\nScalar:")
print("Shape:", scalar_shape, "Rank:", scalar_rank, "Size:", scalar_size)

print("\nMatrix:")
print("Shape:", matrix_shape, "Rank:", matrix_rank, "Size:", matrix_size)

print("\nTensor:")
print("Shape:", tensor_shape, "Rank:", tensor_rank, "Size:", tensor_size)

Vector:
Shape: [4] Rank: 1 Size: 4

Scalar:
Shape: [] Rank: 0 Size: 1

Matrix:
Shape: [2 3] Rank: 2 Size: 6

Tensor:
Shape: [2 2 2] Rank: 3 Size: 8


##### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [30]:
import tensorflow as tf

tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float32)

sess = tf.compat.v1.Session()
tensor1_value = sess.run(tensor1)
tensor2_value = sess.run(tensor2)

print("Tensor 1:\n",tensor1_value)
print("\nTensor 2:\n",tensor2_value)


Tensor 1:
 [[0.02024376 0.76899207 0.05383217 ... 0.01619196 0.5849967  0.01460612]
 [0.41906726 0.8145306  0.6317235  ... 0.55733263 0.4752823  0.9187498 ]
 [0.13452888 0.93715763 0.5274875  ... 0.8994812  0.5418043  0.2340033 ]
 [0.27825558 0.45291996 0.10290205 ... 0.09021378 0.11492252 0.6987332 ]
 [0.39241397 0.65440536 0.05290377 ... 0.2753861  0.49361002 0.2129544 ]]

Tensor 2:
 [[0.14619696 0.20528913 0.368384   ... 0.3559811  0.57277405 0.12540042]
 [0.29488277 0.36479867 0.64533925 ... 0.6325718  0.06968927 0.7721995 ]
 [0.6461791  0.12864041 0.8132862  ... 0.65396345 0.1423701  0.31417906]
 [0.29586315 0.62227273 0.1227262  ... 0.8956716  0.28186107 0.26218796]
 [0.8690783  0.7324915  0.16243398 ... 0.56842697 0.09731209 0.98287165]]


##### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [29]:
matrix_multiplication_result = tf.matmul(tensor1, tf.transpose(tensor2))
sess = tf.compat.v1.Session()
result = sess.run(matrix_multiplication_result)
print("Matrix multiplication result:\n",result)

Matrix multiplication result:
 [[70.527336 70.107544 72.52654  71.525276 79.655464]
 [76.30344  70.96175  76.251656 70.39782  82.47867 ]
 [76.7223   72.924995 77.71913  75.66389  81.15171 ]
 [73.1607   74.39006  79.54282  74.15027  81.5573  ]
 [71.430504 69.09885  75.971924 72.78395  77.352234]]


##### 5. Multiply the two tensors you created in 3 using dot product.

In [32]:
tensor2_reshaped = tf.reshape(tensor2, [300, 5])
dot_product_result = tf.tensordot(tensor1, tensor2_reshaped, axes=1)
sess = tf.compat.v1.Session()
result = sess.run(dot_product_result)
print("Dot product result:\n",result)

Dot product result:
 [[72.20374  70.55221  67.55761  72.88498  68.814964]
 [80.69154  75.6477   73.52484  75.92659  77.81783 ]
 [74.86025  75.07703  72.06238  74.87934  72.35481 ]
 [73.122635 72.26059  71.34543  76.92683  71.22512 ]
 [77.06219  72.40884  71.521286 76.82638  72.62781 ]]


##### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [33]:
import tensorflow as tf
tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
sess = tf.compat.v1.Session()
tensor_value = sess.run(tensor)
print("Tensor values:",tensor_value)


Tensor values: [[[0.97847927 0.7221184  0.73543155]
  [0.8285693  0.895944   0.08531463]
  [0.50707567 0.75155604 0.3375374 ]
  ...
  [0.9213853  0.2731433  0.45559144]
  [0.9039563  0.9636191  0.12951219]
  [0.30465984 0.47995794 0.66440547]]

 [[0.60646117 0.32544982 0.47417104]
  [0.42668438 0.6804249  0.32489157]
  [0.873392   0.58431625 0.82819223]
  ...
  [0.27867806 0.55014586 0.5460228 ]
  [0.34530532 0.23290169 0.14335835]
  [0.76687753 0.64185965 0.7148682 ]]

 [[0.97997177 0.35478568 0.9630947 ]
  [0.80602276 0.25458896 0.20050335]
  [0.12704551 0.9548582  0.6191722 ]
  ...
  [0.03908718 0.7196462  0.08705604]
  [0.42363358 0.15122223 0.78844154]
  [0.8510518  0.557117   0.02922857]]

 ...

 [[0.76408184 0.49782407 0.08758283]
  [0.804219   0.0573436  0.44361353]
  [0.45256603 0.9432602  0.44489288]
  ...
  [0.49705303 0.40367556 0.3964157 ]
  [0.11628187 0.9323095  0.48297822]
  [0.24967694 0.8453021  0.7631316 ]]

 [[0.9928235  0.43785655 0.7565563 ]
  [0.20062923 0.859560

##### 7. Find the min and max values of the tensor you created in 6.

In [34]:
min_value = tf.reduce_min(tensor)
max_value = tf.reduce_max(tensor)
sess = tf.compat.v1.Session()
min_val, max_val = sess.run([min_value, max_value])
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Minimum value: 5.00679e-06
Maximum value: 0.99998367


##### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [36]:
import tensorflow as tf

tensor = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
squeezed_tensor = tf.squeeze(tensor)

print("Original Tensor Shape:", tensor.shape)
print("Squeezed Tensor Shape:", squeezed_tensor.shape)

Original Tensor Shape: (1, 224, 224, 3)
Squeezed Tensor Shape: (224, 224, 3)


##### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [40]:
import tensorflow as tf

values = [3, 7, 2, 9, 1, 5, 8, 4, 6, 0]
tensor = tf.constant(values, dtype=tf.int32)
max_value_index = tf.argmax(tensor)

sess = tf.compat.v1.Session()
max_index = sess.run(max_value_index)

print("Index of maximum value:", max_index)

Index of maximum value: 3


##### 10. One-hot encode the tensor you created in 9.

In [42]:
max_value = tf.reduce_max(tensor)
sess = tf.compat.v1.Session()
one_hot_encoded = tf.one_hot(tensor, depth=max_value+1)
one_hot_encoded_result = sess.run(one_hot_encoded)
print("One-hot encoded tensor:\n",one_hot_encoded_result)

One-hot encoded tensor:
 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
